### ISSUE TITLE
An attempt is made to create the root directory

### ISSUE THREAD

**Issue by nathan-osman** [UnnoTed/fileb0x#11]
My directory structure looks something like this:

    .
    ├── b0x.yaml
    └── server
        ├── ab0x.go
        └── static
            └── css
                └── styles.min.css

`b0x.yaml` contains the following:

    pkg: server
    dest: server
    compression:
      compress: true
    custom:
      - files:
        - server/static
        base: server

However, when I generate `server/ab0x.go`, the following is added to `init()`:

    err = FS.Mkdir(CTX, "/", 0777)
    if err != nil {
      log.Fatal(err)
    }

This is a problem because [attempting to create the root directory results in an error](https://github.com/golang/net/blob/feeb485667d1fdabe727840fe00adc22431bc86e/webdav/file.go#L250).

**Comment by nathan-osman** [comment]
I have found a workaround in the meantime:

    prefix: static
    base: server/static

**Comment by UnnoTed** [comment]
Hi, thanks for reporting this issue, please do a `go get -u github.com/UnnoTed/fileb0x` and try again.

**Comment by nathan-osman** [comment]
Seems to work now, thanks!
