### ISSUE TITLE
Go complains about unused variables

### ISSUE THREAD

**Issue by IanS5** [UnnoTed/fileb0x#14]
When compiling my main file, which imports a file generated with fileb0x, go finds ```err```  ```f``` ```rb``` and ```r``` to be "declared but not used". The only way I found to fix this was to manually delete the variables from inside the generated file.

**Comment by rkakrik** [comment]
Same problem

**Comment by UnnoTed** [comment]
Hey, can you provide the config file that you're using?

**Comment by FernFerret** [comment]
hey @UnnoTed, I actually encountered this today using the following very simple (just started trying out fileb0x) repo [here](https://github.com/FernFerret/b0xexample).

It seems to be related (in my case) to `spread` which was enabled in the `echo` portion of the tutorial. I just wrote mine off as I'm probably doing something wrong with the config, and I'm fine not using split mode, but I'd definitely like to know if I'm doing something wrong!

**Comment by UnnoTed** [comment]
Fixed the unused `err` but couldn't get the `f`, `rb` and `r` to be unused.

**Comment by FernFerret** [comment]
@UnnoTed sorry, I should have clarified, I was only able to get the `err` to reproduce. Was my config valid then?

**Comment by UnnoTed** [comment]
@FernFerret Don't worry, It is valid, I said that i couldn't get the other vars because of OP's issue.
