### ISSUE TITLE
Please tag as v1.0.0 (or whatever)

### ISSUE THREAD

**Issue by coolaj86** [UnnoTed/fileb0x#39]
For the sake of being able to easily track likely breaking changes it would be great to have some tags.

```bash
git tag v1.0.0
git push --tags
```

Since this is already much used and well-tested in the wild, starting at v1.0.0 makes sense to me -  but you do what you like :)

**Comment by barryz** [comment]
+1  

> Modules must be semantically versioned in the form v(major).(minor).(patch), such as v0.1.0, v1.2.3, or v3.0.1. The leading v is required. If using Git, tag released commits with their versions.
