### ISSUE TITLE
webdav file system requires context to open files

### ISSUE THREAD

**Issue by peppage** [UnnoTed/fileb0x#4]
After this commit https://github.com/golang/net/commit/4bb47a1098b37d69980d96237e2ae4ff56bb5a95 it's going to be required to send context. At the very minimum opening files needs to be sent context.Background().

**Comment by UnnoTed** [comment]
Updated, thanks for the notice.
https://github.com/UnnoTed/fileb0x/commit/ef153a030ac18be8597c1387b6dbf62b06c21ebe
