### ISSUE TITLE
too many arguments in call to {FS.Mkdir, FS.OpenFile}

### ISSUE THREAD

**Issue by andreynering** [UnnoTed/fileb0x#6]
This error is happening while compiling the generated source.

Rolling back to https://github.com/UnnoTed/fileb0x/commit/89859f8fda74286e7a8698efe57ba7acee55293c fixed for me.

**Comment by UnnoTed** [comment]
https://github.com/UnnoTed/fileb0x/issues/4

**Comment by andreynering** [comment]
Fixed by updating dependencies, including `golang.org/x/net/webdav`. Thanks
